### ISSUE TITLE
Unable to restore backup - Hard Crash in latest version of Signal

### ISSUE THREAD

**Issue by crimsoncor** [bepaald/signalbackup-tools#124]
I don't think this is necessarily an issue with backuptools, but definitely is an issue with Signal that is being triggered by merging backups. I have backups from two phones that I'm attempting to combine and then restore. The individual backup files work fine, but the combined one seems to trigger a Foreign Key crash loop in Signal when it is restored. When I run
```
--runsqlquery "pragma foreign_key_check"
```
against the merged backup file, everything is reported as fine. However, in the signal crash log I'm seeing 
```
06-11 17:03:19.709  3487  4297 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
06-11 17:03:19.709  3487  4297 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 3487
06-11 17:03:19.709  3487  4297 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
06-11 17:03:19.709  3487  4297 E AndroidRuntime: 	at android.os.AsyncTask$4.done(AsyncTask.java:415)
06-11 17:03:19.709  3487  4297 E AndroidRuntime: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:381)
06-11 17:03:19.709  3487  4297 E AndroidRuntime: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:250)
06-11 17:03:19.709  3487  4297 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:269)
06-11 17:03:19.709  3487  4297 E AndroidRuntime: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
06-11 17:03:19.709  3487  4297 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
06-11 17:03:19.709  3487  4297 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
06-11 17:03:19.709  3487  4297 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
06-11 17:03:19.709  3487  4297 E AndroidRuntime: Caused by: java.lang.IllegalStateException: Foreign Key Constraints cannot be enabled or disabled while there are transactions in progress.  Finish all transactions and release all active database connections first.
06-11 17:03:19.709  3487  4297 E AndroidRuntime: 	at net.zetetic.database.sqlcipher.SQLiteConnectionPool.reconfigure(SQLiteConnectionPool.java:291)
06-11 17:03:19.709  3487  4297 E AndroidRuntime: 	at net.zetetic.database.sqlcipher.SQLiteDatabase.setForeignKeyConstraintsEnabled(SQLiteDatabase.java:2177)
06-11 17:03:19.709  3487  4297 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.SignalDatabase$Companion.runPostBackupRestoreTasks(SignalDatabase.kt:300)
06-11 17:03:19.709  3487  4297 E AndroidRuntime: 	at org.thoughtcrime.securesms.database.SignalDatabase.runPostBackupRestoreTasks(Unknown Source:2)
06-11 17:03:19.709  3487  4297 E AndroidRuntime: 	at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:294)
06-11 17:03:19.709  3487  4297 E AndroidRuntime: 	at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:279)
06-11 17:03:19.709  3487  4297 E AndroidRuntime: 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
06-11 17:03:19.709  3487  4297 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
06-11 17:03:19.709  3487  4297 E AndroidRuntime: 	... 4 more
--------- beginning of system
```
I'm not fully sure how to go about debugging this, now. If I was seeing a foreign key issue with the db schema, there are other posts here in the gitlab issues that have pretty good details on fixing those sorts of issues. But without that info, I'm not really sure what to try next.
Both backups are version 196 and both phones are running the latest version of Signal (6.21.3). I'm running the latest version of signalbackup-tools from the main branch
```
signalbackup-tools (signalbackup-tools) source version 20230611.140940 (OpenSSL)

```

If someone has any suggestions on how to better interrogate sqllite about what the issues might be, it would be much appreciated.

**Comment by bepaald** [comment]
Hi, sorry it's not working.

I'm not immediately sure what could cause this (never seen this error before). Reading the error, I'd guess there is a `BEGIN TRANSACTION` somewhere that isn't closed (committed or rolled back) before trying to set up the key constraints. But I'd think that would indicate a bug in Signal's backup restore process. I don't believe this program leaves any transactions open, but I just forced one to be open at output (I commented out the `COMMIT`) and it yields the same backup file (bit-identical), so I think transactions are automatically closed when closing the database and writing it out. Also, there is [this](https://github.com/signalapp/Signal-Android/issues/12992) recent bug report that has the same issue, which would also suggest a problem with current Signal. (Maybe their solution works for you as well? Looking at the solution, it might also be the same as [this](https://github.com/signalapp/Signal-Android/issues/12963) one).

>The individual backup files work fine, but the combined one seems to trigger a Foreign Key crash loop in Signal when it is restored.

Then again, this would strongly suggest a bug in this program, unfortunately. So, I'm not sure at the moment. I'll need to think about it.

>If someone has any suggestions on how to better interrogate sqllite about what the issues might be, it would be much appreciated.

Well, right now I'm very much undecided on whether there is anything wrong in the database at all. You could, just to be safe, run `pragma_integrity_check` (or use the `--checkdbintegrity` option) to check the database for more problems than just foreign key constraint violations, but I wouldn't expect any useful output.

**Comment by crimsoncor** [comment]
wow thanks for looking into that. I'll definitely update that ticket in the Signal tracker since my issue matches it perfectly. 

With an unmerged backup, Signal crashes immediately after completing the backup but then lets me add my phone number and authenticate if I go through the restore flow again. The behavior is exactly the same with the merged backup, except that with the merged backup, it enters a crash loop after authentication fails and the application never successfully starts.

I did run the additional database checks on the merged backup and it did not show any issues. I will try dumping to html and see what happens. The merged isn't that different since one of the two files I'm combining only has a month worth of messages in it. My base backup is 716MB and the merged is 732MB, so hopefully the diff isn't too gnarly to work through.

I did notice one other interesting thing, which I haven't fully dug into but did make me go hmmm. I swap between different phones semi-regularly so I have a normal backup merge flow. To make my backup, I ran
```
signalbackup-tools oneplus2_signal-2023-06-11-17-36-38_cropped.backup  `cat oneplus2.key` --importthreads ALL --source pixel6a_signal-2023-06-11-06-09-25.backup --sourcepassword `cat atom.key` --output merged_2023-06-11-17-41-25.backup --opassword `cat atom.key`
```
That worked fine and yielded a backup file that reports no errors, though Signal will not work after loading.  The initial file is a backup from my secondary phone that only covers the last month. The pixel6a file is the big 716MB main backup.

Just as an experiment, I tried swapping the order of the backups in the merge
```
signalbackup-tools pixel6a_signal-2023-06-11-06-09-25.backup  `cat atom.key` --importthreads ALL --source oneplus2_signal-2023-06-11-17-36-38_cropped.backup --sourcepassword `cat oneplus2.key` --output merged_2023-06-12-09-04-25.backup --opassword `cat atom.key`
```
and for some reason, that merge does fail with a foreign key error!
```
Checking foreign key constraints...
ERROR Foreign key constraint violated. This will not end well, aborting.
      Please report this error to the program author.
---------------------------------------
| table            | parent    | fkid |
---------------------------------------
| message          | recipient | 3    |
| reaction         | recipient | 0    |
| group_membership | recipient | 0    |
---------------------------------------
A fatal error occurred while trying to import thread 19. Aborting

```
I was going to try removing the record in question and seeing if I could get the merge to work in the opposite direction. I'm kinda puzzled why it the behavior is different based on the ordering of the backup files

**Comment by crimsoncor** [comment]
OKAY! That error was actually pretty relevant. As best I can tell, here is what happened. Thread 19 was a group message. In the oneplus2 backup, a new member had been added to that group.  And that member had apparently reacted to a message in that thread. It appears like that member was not present in the pixel6a backup and that is what was causing the Foreign Key issue when reversing the merge order of the files. 

I went back to the pixel 6a phone, sent a message to the group, and then did another backup. With that new backup, the foreign key error vanished when doing the reverse direction merge. And the resulting merged backup was successfully loaded in Signal (oh, it still crashed after doing the import, but redoing the restore flow a second time did not cause a crash loop).

So it was something, somehow, with signalbackup-tools due to the group mismatch between the two backup files. but I've got everything working now, so I'm pleased. 

Leaving the ticket open for now, in case there is something there you want to dig into. But I seem to be 100% sorted at the moment.

**Comment by bepaald** [comment]
> I think there was only a single bug in the backup tools, but it was manifesting in two different ways.

Well I hope you're right. Very kind to offer to test, I look forward to the results (but no hurry of course, do take your time).

**Comment by crimsoncor** [comment]
Sorry about the long wait. Finally got a chance to test this. with the last build, the database merge works in both directions without any issues or any crash on restore. So it seems like everything was sorted. thanks so much for the quick fix and digging into this!

**Comment by bepaald** [comment]
No worries, it must have been quite a hassle to run the merge twice and restore both just to test. Thanks for reporting back, glad it's solved!

**Comment by MartB** [comment]
I cant use the story tab after restoring or disable them with the same error message: MyStoryDoesNotExistException

```
05-13 16:06:08.840 20350 20419 E BaseJob : org.thoughtcrime.securesms.storage.StoryDistributionListRecordProcessor$MyStoryDoesNotExistException
05-13 16:06:08.840 20350 20419 E BaseJob : 	at org.thoughtcrime.securesms.storage.StoryDistributionListRecordProcessor.getMatching(StoryDistributionListRecordProcessor.java:76)
05-13 16:06:08.840 20350 20419 E BaseJob : 	at org.thoughtcrime.securesms.storage.StoryDistributionListRecordProcessor.getMatching(StoryDistributionListRecordProcessor.java:24)
05-13 16:06:08.840 20350 20419 E BaseJob : 	at org.thoughtcrime.securesms.storage.DefaultStorageRecordProcessor.process(DefaultStorageRecordProcessor.java:51)
05-13 16:06:08.840 20350 20419 E BaseJob : 	at org.thoughtcrime.securesms.storage.StoryDistributionListRecordProcessor.process(StoryDistributionListRecordProcessor.java:24)
05-13 16:06:08.840 20350 20419 E BaseJob : 	at org.thoughtcrime.securesms.jobs.StorageSyncJob.processKnownRecords(StorageSyncJob.java:414)
05-13 16:06:08.840 20350 20419 E BaseJob : 	at org.thoughtcrime.securesms.jobs.StorageSyncJob.performSync(StorageSyncJob.java:293)
05-13 16:06:08.840 20350 20419 E BaseJob : 	at org.thoughtcrime.securesms.jobs.StorageSyncJob.onRun(StorageSyncJob.java:194)
05-13 16:06:08.840 20350 20419 E BaseJob : 	at org.thoughtcrime.securesms.jobs.BaseJob.run(BaseJob.java:31)
05-13 16:06:08.840 20350 20419 E BaseJob : 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:86)
05-13 16:06:08.840 20350 20419 E BaseJob : 	at org.thoughtcrime.securesms.jobmanager.JobRunner.run(JobRunner.java:49)
05-13 16:06:08.841 20350 20419 E JobRunner: [JOB::5bca633c-f6c0-4b67-aafa-cc1790ae024b][StorageSyncJob][1] Job failed with a fatal exception. Crash imminent. (Time Since Submission: 987 ms, Lifespan: 86400000 ms, Run Attempt: 1/3, Queue: StorageSyncingJobs)
05-13 16:06:08.841 20350 20688 D ConversationListDataSou: [size(), UnarchivedConversationListDataSource, OFF] 0 ms
```

**Comment by bepaald** [comment]
>I cant use the story tab after restoring or disable them with the same error message: MyStoryDoesNotExistException

Just wanted to add for completeness that after another user's report with a similar problem (though upon cropping instead of merging (which call some of the same functions)), changes have been made to how stories, and specifically 'my story' is handled. I hope this issue is now fixed.
