### ISSUE TITLE
Conversation crashes Signal after importfromdesktop

### ISSUE THREAD

**Issue by luturnai** [bepaald/signalbackup-tools#143]
Thank you for creating this tool! It is really helpful to get my conversation history back after a sudden bricking of my phone.

I used --importformdesktop to update a backup.
The process gave a couple of warnings about unsupported message types that are already in the issue tracker.
However, after restoring the backup, for exactly one of the conversations, where data was updated from desktop, Signal crashes when I scroll across a particular date boundary. 
Just as Signal should be rendering the date text it crashes. 
The conversation looks correct up until that point, and when I compare with the HTML export nothing out of the ordinary comes next. 
It is just the next day, with basic text messages following.

Any suggestions for how I can go about figuring out what is happening and potentially correct it?

**Comment by bepaald** [comment]
Hi!

Well, that's not good. There were some pretty intense changes to the (desktop) database recently, maybe that has something to do with it. Probably the best thing to do is to get a debuglog from Signal after the crash, hopefully that can point me in the right direction to find the cause. Alternatively, you could run Signal with adb attached, which would basically provide a live debuglog.

Also, maybe since you know the thread and date, you could also check in Signal Desktop (not just the exported html) if there is anything special about the message, an attachment, a reaction, a quote, a mention, anything. The crash generally indicates some data was imported incorrectly (a non-existing recipient) and it's possible the htmlexport simply skips the incorrect data.

Sorry for your trouble, the desktop import was a difficult function to implement, I hope I manage to fix this. Thanks!

**Comment by luturnai** [comment]
When I check Signal Desktop I see nothing special about the messages that hasn't been used previously in the conversation. Text, emojis, reaction emojis, message replies, images. I noticed a few days further down, there are some voice messages, but those have appeared in this and other conversations before without issue. Although all the other voice messages were from the backup, and only this conversation has newer voice messages from the desktop application. 

I extracted a log via adb while triggering the bug. Below I have added the FATAL EXCEPTION. Mentions "Invalid ServiceID". Let me know if it would be helpful to search the log for other keywords or more from the same PID.

And no need to apologize - you have made a lot of effort developing this as far as you have. I realize this is very unsupported by Signal and that your work is aiming at a moving target. I appreciate your effort and how soon you were able to make suggestions for next steps.


```
09-13 23:04:25.409 30183 32316 E AndroidRuntime: FATAL EXCEPTION: signal-FixedSizePagingController
09-13 23:04:25.409 30183 32316 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 30183
09-13 23:04:25.409 30183 32316 E AndroidRuntime: java.lang.IllegalArgumentException: Invalid ServiceId!
09-13 23:04:25.409 30183 32316 E AndroidRuntime:  at org.whispersystems.signalservice.api.push.ServiceId$Companion.parseOrThrow(ServiceId.kt:83)
09-13 23:04:25.409 30183 32316 E AndroidRuntime:  at org.whispersystems.signalservice.api.push.ServiceId.parseOrThrow(ServiceId.kt:0)
09-13 23:04:25.409 30183 32316 E AndroidRuntime:  at org.thoughtcrime.securesms.database.MentionUtil.lambda$bodyRangeListToMentions$3(MentionUtil.java:114)
09-13 23:04:25.409 30183 32316 E AndroidRuntime:  at org.thoughtcrime.securesms.database.MentionUtil.$r8$lambda$_S0kHabr70qrh9YkIvgwaNG2vjg(MentionUtil.java:0)
09-13 23:04:25.409 30183 32316 E AndroidRuntime:  at org.thoughtcrime.securesms.database.MentionUtil$$ExternalSyntheticLambda1.apply(R8$$SyntheticClass:0)
09-13 23:04:25.409 30183 32316 E AndroidRuntime:  at com.annimon.stream.operator.ObjMap.nextIteration(ObjMap.java:24)
09-13 23:04:25.409 30183 32316 E AndroidRuntime:  at com.annimon.stream.iterator.LsaIterator.next(LsaIterator.java:22)
09-13 23:04:25.409 30183 32316 E AndroidRuntime:  at com.annimon.stream.Stream.toList(Stream.java:1539)
09-13 23:04:25.409 30183 32316 E AndroidRuntime:  at org.thoughtcrime.securesms.database.MentionUtil.bodyRangeListToMentions(MentionUtil.java:117)
09-13 23:04:25.409 30183 32316 E AndroidRuntime:  at org.thoughtcrime.securesms.database.MessageTable$Companion.parseQuoteMentions(MessageTable.kt:535)
09-13 23:04:25.409 30183 32316 E AndroidRuntime:  at org.thoughtcrime.securesms.database.MessageTable$Companion.access$parseQuoteMentions(MessageTable.kt:157)
09-13 23:04:25.409 30183 32316 E AndroidRuntime:  at org.thoughtcrime.securesms.database.MessageTable$MmsReader.getQuote(MessageTable.kt:5382)
09-13 23:04:25.409 30183 32316 E AndroidRuntime:  at org.thoughtcrime.securesms.database.MessageTable$MmsReader.getMediaMmsMessageRecord(MessageTable.kt:5285)
09-13 23:04:25.409 30183 32316 E AndroidRuntime:  at org.thoughtcrime.securesms.database.MessageTable$MmsReader.getCurrent(MessageTable.kt:5134)
09-13 23:04:25.409 30183 32316 E AndroidRuntime:  at org.thoughtcrime.securesms.database.MessageTable$MmsReader.getNext(MessageTable.kt:5124)
09-13 23:04:25.409 30183 32316 E AndroidRuntime:  at org.thoughtcrime.securesms.database.MessageTable$MmsReader$ReaderIterator.next(MessageTable.kt:5428)
09-13 23:04:25.409 30183 32316 E AndroidRuntime:  at org.thoughtcrime.securesms.database.MessageTable$MmsReader$ReaderIterator.next(MessageTable.kt:5422)
09-13 23:04:25.409 30183 32316 E AndroidRuntime:  at org.thoughtcrime.securesms.conversation.v2.data.ConversationDataSource.load(ConversationDataSource.kt:1855)
09-13 23:04:25.409 30183 32316 E AndroidRuntime:  at org.signal.paging.FixedSizePagingController.lambda$onDataNeededAroundIndex$1(FixedSizePagingController.java:111)
09-13 23:04:25.409 30183 32316 E AndroidRuntime:  at org.signal.paging.FixedSizePagingController.$r8$lambda$pQWvrV6w7QQq3SnkCgnHNDTtP_I(FixedSizePagingController.java:0)
09-13 23:04:25.409 30183 32316 E AndroidRuntime:  at org.signal.paging.FixedSizePagingController$$ExternalSyntheticLambda2.run(R8$$SyntheticClass:0)
09-13 23:04:25.409 30183 32316 E AndroidRuntime:  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
09-13 23:04:25.409 30183 32316 E AndroidRuntime:  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
09-13 23:04:25.409 30183 32316 E AndroidRuntime:  at java.lang.Thread.run(Thread.java:1012)
09-13 23:04:25.409 30183 32316 E AndroidRuntime:  at org.signal.core.util.concurrent.SignalExecutors$1.run(SignalExecutors.java:32)

```

**Comment by bepaald** [comment]
Thanks, that looks useful.

The error seems to have to do with a (quoted) mention (like: @luturnai). At a first, very quick test I don't see any obvious problems in this code (when importing from desktop into a complete Android backup the imported messages appear identical to the Android messages in the database), but I will investigate further later today.

A couple of questions if you happen to know:

- Is it possible the offending message contains a mention, specifically a mention in a quote? Is the offending thread at least a group-conversation? I'm not sure how many messages Signal preloads when scrolling, so it might be a bit further on. If so, is there anything special about that message as far as you can tell (maybe members are mentioned that do not exist in your Android backup, or are not part of the group).
- If you had to guess which message was the problem, could you say around what date that message was sent? Was your Signal Desktop fully up to date at that point? 
- When running the import, were you using a recent version of this tool (after 5 sept)?

Thanks!

**Comment by luturnai** [comment]
Thank you for the suggestions.

I don't see any quoted mentions when I look through data in the desktop version. When I search for @ in the conversation it finds 0 instances. If quotes are likely to play a role even in other circumstances there may be another possibility: There is a quote of a message with two images in it, one of them modified with a green line drawn on it, two days past the boundary.

The conversation is with a single person, not a group. The conversation and person already exist in the backup.

I think Signal Desktop was updated to the newest version when I ran signalbackup-tool. I run signal desktop on debian 11 with automatic updates. I have added the Signal repo for debian to the source list. So it should have been up to date. However, checking just a moment ago, I see that 6.30.2 is available and has not yet been installed (is 6.30.1 at present). 

I run the signalbackup-tools with nix using the following command:

`sudo nix-shell -p signalbackup-tools -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/master.tar.gz`

I hope that the tool version is relatively recent by grabbing nixpkgs from github. If you know another way of running nix that is likely to have a more recent version of signalbackup-tools I am very interested. I am new to nix so there was some trial and error figuring out how it likes things. It looks like a very convenient way of running dependency rich tools without installing lots of stuff that I don't need for anything else.

**Comment by bepaald** [comment]
Well, the fact that the conversation is with a single person shoots down my previous theory (mentions are only possible in groups I think), but I have a new theory. Still having to do with quotes and _another_ bug in my code around quotes.

My new theory is a quoted styled text (anything **bold**, _italic_ or whatever is supported these days). When that feature was introduced I quickly supported it, but as usual forgot about quoted messages. And of course, like mentions, styling is handled just a bit differently inside quotes. 

I've just added additional code for that for dealing with these quotes, so you'd need to update again. I realize it is a bit of a hassle, but could you try actually restoring a newly generated backup and checking if the error is gone? If not, maybe you could also check if the exception shown by adb is still the same.

I have no experience with nixpkgs myself, but the version of this tool (= the date) is printed as the first line of output whenever you run it. It needs to be > 20230915 now. If nixpkgs doesn't provide the latest version, you could compile yourself, the program has only very few and common dependencies. But I don't know if the Debian versions of the packages are recent enough (while this program generally works with a lot of older versions, the `--importfromdesktop` might fail if the sqlite version used is much older than the one used internally by Signal Desktop).

Thanks!

**Comment by luturnai** [comment]
I see a single example of bold text formatting in a message and later a quote of that same message in the conversation. The quote is 5 days after the point where the crash happens, so it seems a plausible cause. 

I had not caught that there was formatting of text. I think it may be the first time I have come across formatting in any of my conversations.

Nix built updates from yesterday upon launch yesterday. However it has not built the update from today when I ran it just now. So for now I wait and see when it becomes available.

**Comment by bepaald** [comment]
That sounds good, I have very high hopes for this. Let's just hope it's the only problem with the import, and not just the first...

**Comment by luturnai** [comment]
Attempting to importfromdesktop with source version 20230915.165434 produces following error:

```
Error : During sqlite3_prepare_v2(): malformed database schema (messages_on_insert_insert_mentions) - near ">>": syntax error
  Query: "SELECT 1 FROM PRAGMA_TABLE_XINFO('conversations') WHERE name == 'serviceId'"
Error : During sqlite3_prepare_v2(): malformed database schema (messages_on_insert_insert_mentions) - near ">>": syntax error
  Query: "SELECT 1 FROM PRAGMA_TABLE_XINFO('conversations') WHERE name == 'uuid'"
Error : During sqlite3_prepare_v2(): malformed database schema (messages_on_insert_insert_mentions) - near ">>": syntax error
  Query: "SELECT 1 FROM PRAGMA_TABLE_XINFO('messages') WHERE name == 'sourceServiceId'"
Error : During sqlite3_prepare_v2(): malformed database schema (messages_on_insert_insert_mentions) - near ">>": syntax error
  Query: "SELECT 1 FROM PRAGMA_TABLE_XINFO('messages') WHERE name == 'sourceUuid'"
  Using range: 2023-08-21 20:00:00 - 2023-10-01 00:00:00 (1692644400000 - 1696114800000)
Error : During sqlite3_prepare_v2(): malformed database schema (messages_on_insert_insert_mentions) - near ">>": syntax error
  Query: "SELECT MAX(MAX(json_extract(json, '$.received_at_ms')),MAX(received_at)) FROM messages"
Error : During sqlite3_prepare_v2(): malformed database schema (messages_on_insert_insert_mentions) - near ">>": syntax error
  Query: "SELECT rowid,id,e164,type,LOWER() AS 'uuid',groupId,IFNULL(json_extract(json,'$.isArchived'), false) AS 'is_archived',IFNULL(json_extract(json,'$.isPinned'), false) AS 'is_pinned',IFNULL(json_extract(json,'$.groupId'),'') AS 'json_groupId',IFNULL(json_extract(json,'$.derivedGroupV2Id'),'') AS 'derivedGroupV2Id',IFNULL(json_extract(json,'$.groupVersion'), 1) AS groupVersion FROM conversations WHERE json_extract(json, '$.messageCount') > 0"

```

**Comment by bepaald** [comment]
The `malformed database schema` is a bit of a weird error, but in practice it is always caused by using a too old sqlite3 version (for example #133). Note it's not something I can code around, it's the Signal Desktop database that was created using a newer version and the old version simply cannot read the newer one. I'm afraid you need to update sqlite3.

Was this from nixpkgs, or a self compile? What version of sqlite3 does Debian provide?

**Comment by luturnai** [comment]
Good call about sqlite3 version. I switched from nixpkgs to compiling myself because I was getting impatient waiting for their rollouts of updates. This explains why I am seeing an issue with sqlite3. I have version 3.34.1, which is obviously lower than 3.39.4.

I will try out the dockerfile or run a VM with a newer OS version next and see if I get better results.

**Comment by bepaald** [comment]
If I'm seeing it correctly, the nixpkg version seems to have been updated ([here](https://github.com/NixOS/nixpkgs/commit/8b080367f934ac7726a9404567a5a817990a0009)), so it might be easier to try that for now.

**Comment by BernwardWeigand** [comment]
Hi @bepaald ,

let me thank you first for the great tool, the decrypting and the xport to HTML work perfectly. I just bought you a Ko-fi. 😉 
Unfortunately I am experiencing similar Issues importing conversations from the desktop client. 😅  The export to HTML works pretty well and all chats look fine.  
I am using Signal desktop for Windows (version 6.30.2) and the Signal Android app (version 6.32.5).
The ADB errors stack trace  seem to differ a bit from the one @luturnai had posted:
```
2023-09-20 09:13:06.832  6084-10896 AndroidRuntime          org.thoughtcrime.securesms           E  FATAL EXCEPTION: AsyncTask #5
                                                                                                    Process: org.thoughtcrime.securesms, PID: 6084
                                                                                                    java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                                                                    	at android.os.AsyncTask$3.done(AsyncTask.java:355)
                                                                                                    	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
                                                                                                    	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
                                                                                                    	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
                                                                                                    	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:246)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                                                                                                    	at java.lang.Thread.run(Thread.java:784)
                                                                                                    Caused by: java.lang.NegativeArraySizeException: -235780801
                                                                                                    	at org.thoughtcrime.securesms.backup.BackupRecordInputStream.readFrame(BackupRecordInputStream.java:164)
                                                                                                    	at org.thoughtcrime.securesms.backup.BackupRecordInputStream.readFrame(BackupRecordInputStream.java:92)
                                                                                                    	at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:93)
                                                                                                    	at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:71)
                                                                                                    	at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:292)
                                                                                                    	at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:282)
                                                                                                    	at android.os.AsyncTask$2.call(AsyncTask.java:334)
                                                                                                    	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                                                                                                    	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:246) 
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187) 
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152) 
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
                                                                                                    	at java.lang.Thread.run(Thread.java:784) 
2023-09-20 09:13:06.838  6084-10896 SignalUncaughtException org.thoughtcrime.securesms           E  
                                                                                                    java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                                                                    	at android.os.AsyncTask$3.done(AsyncTask.java:355)
                                                                                                    	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
                                                                                                    	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
                                                                                                    	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
                                                                                                    	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:246)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                                                                                                    	at java.lang.Thread.run(Thread.java:784)
                                                                                                    Caused by: java.lang.NegativeArraySizeException: -235780801
                                                                                                    	at org.thoughtcrime.securesms.backup.BackupRecordInputStream.readFrame(BackupRecordInputStream.java:164)
                                                                                                    	at org.thoughtcrime.securesms.backup.BackupRecordInputStream.readFrame(BackupRecordInputStream.java:92)
                                                                                                    	at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:93)
                                                                                                    	at org.thoughtcrime.securesms.backup.FullBackupImporter.importFile(FullBackupImporter.java:71)
                                                                                                    	at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:292)
                                                                                                    	at org.thoughtcrime.securesms.registration.fragments.RestoreBackupFragment$2.doInBackground(RestoreBackupFragment.java:282)
                                                                                                    	at android.os.AsyncTask$2.call(AsyncTask.java:334)
                                                                                                    	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                                                                                                    	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:246) 
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187) 
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152) 
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
                                                                                                    	at java.lang.Thread.run(Thread.java:784)
````
Also the Timestamp of the generated backup seems to be broken the start of the unix epoch is displayed as the backup date in the Android app:
![image](https://github.com/bepaald/signalbackup-tools/assets/26571395/3b378722-dc5d-49ae-815f-3848363f9200)

**Comment by bepaald** [comment]
Hi @BernwardWeigand! I feel this is such a different problem, I've created a new issue, so please join me at #145. Thanks!

**Comment by bepaald** [comment]
That's great news, thanks for reporting back. And thank you very much for reporting this problem and providing such relevant info, that's what really helps improve this program. Thanks again!
