### ISSUE TITLE
JSONException at Signal Android every time picture or video is clicked after --importfromdesktop

### ISSUE THREAD

**Issue by kwinz** [bepaald/signalbackup-tools#264]
Hi,

I imported chat logs from the Signal Desktop application into a backup. After re-ingesting that patched backup file into the Android Signal app the app now crashes every time I maximize a video or picture with a `JSONException`.

1. the chat logs look good
2. Crashes happens reliably 100% every time I maximize any photo in Signal on the mobile phone
3. The crashes happen both when maximizing media that I received after restoring from the patched backup file and media that I received before restoring the patched backup file.
4. And the same pictures and videos maximize and play just fine on the Desktop app after I relinked it. The crashes happen only on Android.
5. Audio files or other files (e.g. PDF) from contacts are not affected - they play/open just fine

In summary: every works, except that for the pictures and videos on Android

Crash log with Stacktrace:

```
type: crash
osVersion: google/cheetah/cheetah:15/AP3A.241105.007/2024120400:user/release-keys
package: org.thoughtcrime.securesms:148900, targetSdk 34
process: org.thoughtcrime.securesms
processUptime: 70067 + 293 ms
installer: com.android.vending

org.json.JSONException: Value {"low":294452311,"high":403,"unsigned":true} at upload_timestamp of type java.lang.String cannot be converted to long
	at org.json.JSON.typeMismatch(JSON.java:101)
	at org.json.JSONObject.getLong(JSONObject.java:526)
	at org.thoughtcrime.securesms.util.JsonUtils$SaneJSONObject.getLong(JsonUtils.java:72)
	at org.thoughtcrime.securesms.database.AttachmentTable.getAttachments(AttachmentTable.kt:1908)
	at org.thoughtcrime.securesms.database.MessageTable$MmsReader.getMediaMmsMessageRecord(MessageTable.kt:5315)
	at org.thoughtcrime.securesms.database.MessageTable$MmsReader.getCurrent(MessageTable.kt:5238)
	at org.thoughtcrime.securesms.database.MessageTable$MmsReader.getNext(MessageTable.kt:5233)
	at org.thoughtcrime.securesms.database.MessageTable$MmsReader$ReaderIterator.next(MessageTable.kt:5471)
	at org.thoughtcrime.securesms.database.MessageTable$MmsReader$ReaderIterator.next(MessageTable.kt:5465)
	at org.thoughtcrime.securesms.mediapreview.MediaPreviewRepository.getAttachments$lambda$4(MediaPreviewRepository.kt:1628)
	at org.thoughtcrime.securesms.mediapreview.MediaPreviewRepository.$r8$lambda$jP6qsBpljSvKzrmvaRIOQ1zTKXs(MediaPreviewRepository.kt:0)
	at org.thoughtcrime.securesms.mediapreview.MediaPreviewRepository$$ExternalSyntheticLambda3.call(R8$$SyntheticClass:0)
	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:25)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
	at org.signal.core.util.concurrent.SignalExecutors$NumberedThreadFactory$1.run(SignalExecutors.java:109)
	at [[ ↑↑ Original Trace ↑↑ ]].(:0)
	at [[ ↓↓ Exception Message ↓↓ ]].(:0)
	at Value {"low":294452311,"high":403,"unsigned":true} at upload_timestamp of type java.lang.String cannot be converted to long.(:0)
```

Command used to import from Signal desktop and patch the backup file:
`.\signalbackup-tools_win.exe .\signal-2024-12-06-17-59-55-unpatched.backup <removedkey> --importfromdesktop --output signal-2024-12-06-17-59-55.backup`

```
*** Starting log: 2024-12-06 18:04:06 ***
signalbackup-tools (C:\Users\<user>\Downloads\signal-2024-12-06\signalbackup-tools_win.exe) source version 20241205.235013 (Win) (SQlite: 3.47.1, OpenSSL: OpenSSL 3.4.0 22 Oct 2024)
BACKUPFILE VERSION: 1
BACKUPFILE SIZE: 6422716
COUNTER: 1407308420
Reading backup file: 100.0%... done!
Database version: 256
Trying to match conversation (1/55) (type: private)
[Warning]: Failed to find matching thread for conversation, creating. (id: 09450f4c-fc8a-4846-ba0b-<removed>, thread_id: 15)
 - Importing 30 messages into thread._id 15
Trying to match conversation (2/55) (type: private)
[Warning]: Failed to find matching thread for conversation, creating. (id: be1516a7-773a-4da4-bb47-<removed>, thread_id: 16)
 - Importing 261 messages into thread._id 16
Trying to match conversation (3/55) (type: private)
[Warning]: Failed to find matching thread for conversation, creating. (id: d4890651-6917-4d01-83f3-<removed>, thread_id: 17)
 - Importing 5740 messages into thread._id 17
[Warning]: Failed to get number of attachments in quoted message. Skipping
[Warning]: Failed to get number of attachments in quoted message. Skipping
[Warning]: Failed to get number of attachments in quoted message. Skipping
[Warning]: Failed to get number of attachments in quoted message. Skipping
[Warning]: Failed to get number of attachments in quoted message. Skipping
[Warning]: Failed to get number of attachments in quoted message. Skipping
Trying to match conversation (4/55) (type: private)
[Warning]: Failed to find matching thread for conversation, creating. (id: 1b24fc43-5c5e-47b3-bff0-<removed>, thread_id: 18)
 - Importing 1948 messages into thread._id 18
[Warning]: Failed to get number of attachments in quoted message. Skipping
[Warning]: Failed to get number of attachments in quoted message. Skipping
[Warning]: Failed to get number of attachments in quoted message. Skipping
[Warning]: Failed to get number of attachments in quoted message. Skipping
Skipping conversation, conversation has no messages (5/55)
Trying to match conversation (6/55) (type: private)
[Warning]: Failed to find matching thread for conversation, creating. (id: d4ca078b-4c23-4664-817c-<removed>, thread_id: 19)
 - Importing 45 messages into thread._id 19
Trying to match conversation (7/55) (type: private)
[Warning]: Failed to find matching thread for conversation, creating. (id: 720a5cb4-a938-4d54-ae5c-<removed>, thread_id: 20)
 - Importing 866 messages into thread._id 20
Trying to match conversation (8/55) (type: private)
[Warning]: Failed to find matching thread for conversation, creating. (id: f171b1ae-2358-4472-8a05-<removed>, thread_id: 21)
 - Importing 22 messages into thread._id 21
Trying to match conversation (9/55) (type: private)
[Warning]: Failed to find matching thread for conversation, creating. (id: 4b8e0f7b-069b-4d3a-81ef-<removed>, thread_id: 22)
 - Importing 839 messages into thread._id 22
[Warning]: Failed to get number of attachments in quoted message. Skipping
[Warning]: Failed to get number of attachments in quoted message. Skipping
[Warning]: Failed to get number of attachments in quoted message. Skipping
[Warning]: Failed to get number of attachments in quoted message. Skipping
[Warning]: Failed to get number of attachments in quoted message. Skipping
[Warning]: Failed to get number of attachments in quoted message. Skipping
[Warning]: Failed to get number of attachments in quoted message. Skipping
[Warning]: Failed to get number of attachments in quoted message. Skipping
[Warning]: Failed to get number of attachments in quoted message. Skipping
[Warning]: Failed to get number of attachments in quoted message. Skipping
Trying to match conversation (10/55) (type: private)
[Warning]: Failed to find matching thread for conversation, creating. (id: d3c0a1b1-51e3-46da-be1b-<removed>, thread_id: 23)
<similar messages ommited>
Trying to match conversation (55/55) (type: private)
[Warning]: Failed to find matching thread for conversation, creating. (id: 6b221983-3a94-4ca1-ade1-<removed>, thread_id: 54)
 - Importing 18 messages into thread._id 54
[Warning]: Profile data empty. Not updating group recipient.
[Warning]: Failed to update profile data.
[Warning]: Profile data empty. Not updating group recipient.
[Warning]: Failed to update profile data.
reorderMmsSmsIds...ok
updateThreadsEntries
  Dealing with thread id: 42, 49, 29, 46, 48, 33, 22, 18, 47, 41, 40, 15, 38, 21, 50, 54, 44, 17, 45, 25, 28, 23, 35, 26, 52, 19, 39, 43, 32, 20, 30, 31, 37, 53, 36, 24, 27, 16, 34, 51, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 14, 13
Checking foreign key constraints... ok
Checking database integrity (full)... ok

Exporting backup to 'signal-2024-12-06-17-59-55.backup'
Writing HeaderFrame...
Writing DatabaseVersionFrame...
Writing SqlStatementFrame(s)...
  Dealing with table 'attachment'... 444/6808 entries...
Ignoring request to clear attachmentdata as it is not backed by file
  Dealing with table 'attachment'... 737/6808 entries...
Ignoring request to clear attachmentdata as it is not backed by file
  Dealing with table 'attachment'... 771/6808 entries...
Ignoring request to clear attachmentdata as it is not backed by file
  Dealing with table 'attachment'... 827/6808 entries...
Ignoring request to clear attachmentdata as it is not backed by file
  Dealing with table 'attachment'... 830/6808 entries...
Ignoring request to clear attachmentdata as it is not backed by file
  Dealing with table 'attachment'... 1323/6808 entries...
Ignoring request to clear attachmentdata as it is not backed by file
  Dealing with table 'attachment'... 2049/6808 entries...
Ignoring request to clear attachmentdata as it is not backed by file
  Dealing with table 'attachment'... 2942/6808 entries...
Ignoring request to clear attachmentdata as it is not backed by file
  Dealing with table 'attachment'... 2967/6808 entries...
Ignoring request to clear attachmentdata as it is not backed by file
  Dealing with table 'attachment'... 3337/6808 entries...
Ignoring request to clear attachmentdata as it is not backed by file
  Dealing with table 'attachment'... 3338/6808 entries...
Ignoring request to clear attachmentdata as it is not backed by file
  Dealing with table 'attachment'... 4813/6808 entries...
Ignoring request to clear attachmentdata as it is not backed by file
  Dealing with table 'attachment'... 4814/6808 entries...
Ignoring request to clear attachmentdata as it is not backed by file
  Dealing with table 'attachment'... 4917/6808 entries...
Ignoring request to clear attachmentdata as it is not backed by file
  Dealing with table 'attachment'... 4918/6808 entries...
Ignoring request to clear attachmentdata as it is not backed by file
  Dealing with table 'attachment'... 4919/6808 entries...
Ignoring request to clear attachmentdata as it is not backed by file
  Dealing with table 'attachment'... 4920/6808 entries...
Ignoring request to clear attachmentdata as it is not backed by file
  Dealing with table 'attachment'... 5283/6808 entries...
Ignoring request to clear attachmentdata as it is not backed by file
  Dealing with table 'attachment'... 6543/6808 entries...
Ignoring request to clear attachmentdata as it is not backed by file
  Dealing with table 'attachment'... 6808/6808 entries...done
  Dealing with table 'avatar_picker'... 0/0 entries...done
  Dealing with table 'recipient'... 507/507 entries...done
  Dealing with table 'thread'... 54/54 entries...done
  Dealing with table 'message'... 47074/47074 entries...done
  Dealing with table 'call'... 0/0 entries...done
  Dealing with table 'call_link'... 0/0 entries...done
  Dealing with table 'cds'... 0/0 entries...done
  Dealing with table 'chat_colors'... 0/0 entries...done
  Dealing with table 'chat_folder'... 1/1 entries...done
  Dealing with table 'chat_folder_membership'... 0/0 entries...done
  Dealing with table 'distribution_list'... 1/1 entries...done
  Dealing with table 'distribution_list_member'... 0/0 entries...done
  Dealing with table 'donation_receipt'... 0/0 entries...done
  Dealing with table 'drafts'... 0/0 entries...done
  Dealing with table 'emoji_search'... 0/0 entries...done
  Dealing with table 'groups'... 13/13 entries...done
  Dealing with table 'group_membership'... 242/242 entries...done
  Dealing with table 'group_receipts'... 30352/30352 entries...done
  Dealing with table 'identities'... 362/362 entries...done
  Dealing with table 'in_app_payment'... 0/0 entries...done
  Dealing with table 'in_app_payment_subscriber'... 0/0 entries...done
  Dealing with table 'kyber_prekey'... 202/202 entries...done
  Dealing with table 'mention'... 410/410 entries...done
  Dealing with table 'msl_payload'... 0/0 entries...done
  Dealing with table 'msl_message'... 0/0 entries...done
  Dealing with table 'msl_recipient'... 0/0 entries...done
  Dealing with table 'name_collision'... 2/2 entries...done
  Dealing with table 'name_collision_membership'... 20/20 entries...done
  Dealing with table 'notification_profile'... 0/0 entries...done
  Dealing with table 'notification_profile_allowed_members'... 0/0 entries...done
  Dealing with table 'notification_profile_schedule'... 0/0 entries...done
  Dealing with table 'payments'... 0/0 entries...done
  Dealing with table 'pending_pni_signature_message'... 0/0 entries...done
  Dealing with table 'pending_retry_receipts'... 0/0 entries...done
  Dealing with table 'reaction'... 9456/9456 entries...done
  Dealing with table 'remapped_recipients'... 0/0 entries...done
  Dealing with table 'remapped_threads'... 0/0 entries...done
  Dealing with table 'remote_megaphone'... 0/0 entries...done
  Dealing with table 'sender_key_shared'... 0/0 entries...done
  Dealing with table 'sender_keys'... 0/0 entries...done
  Dealing with table 'sticker'... 78/78 entries...done
  Dealing with table 'storage_key'... 8/8 entries...done
  Dealing with table 'story_sends'... 0/0 entries...done
Writing SharedPrefFrame(s)...
Writing KeyValueFrame(s)...
Writing Avatars...
Writing EndFrame...
Done! Wrote 3468578949 bytes.

```

**Comment by kwinz** [comment]
Correction: not every chat log is affected. I have several that allows me to open pictures/videos just fine.
Affected seem to be 4 chats (1 direct message, and 3 groups). Other direct message logs and other group logs don't exhibit this problem.

**Comment by bepaald** [comment]
Hi! Thanks for the detailed report and sorry for your trouble.

Just from reading your report, I have a good idea what is happening here, I've seen similar issues before (but on other fields than `upload_timestamp`). For some reason, in some people's databases, certain large numbers are saved as a '[json_long](https://stackoverflow.com/questions/38577028/datatype-long-what-does-high-and-low-mean/56588888#56588888)' instead of just the number. It's hard to code for, since it doesn't happen in my data, but with your report I should be able to fix this quite easily.

I am not at home at the moment, but will work on this as soon as I have a bit of time. Maybe tomorrow, but probably Sunday. I might have some additional questions if things turn out to be more complicated than I think.

When I fix this, will you be able to redo the import process again, or should I try to get your current backup fixed?

Thanks!

**Comment by kwinz** [comment]
Hi! Thanks for the detailed and fast reply even on the weekend! I would love to try with a fixed version!

The only thing I am unsure is if I can just rerun the same `.\signalbackup-tools_win.exe  --importfromdesktop <..>` command, because after I restored the patched backup file with the data from Signal Desktop, I was automatically signed out on Signal Desktop and I had to relink the Signal Dektop app to the new Android installation. I am not sure if the bad data has now spread to the Signal Desktop installation.
Can I reimport from the Signal Desktop app with the same command as before or do I need to restore a backup first? I kept a copy from `C:\Users\<user>\AppData\Roaming\Signal` directory from right before I patched the Android backup file. And I kept the output of `sigtop export-key` from right before patching the backup file.

I am not sure if fixing the data inside the backup is easier. I am okay with losing the next two or 3 days of messages.

 Thank you again very much for the encouraging reply! Much appreciated!

**Comment by bepaald** [comment]
Thanks again for your report, I believe I have now fixed the issue. 

>The only thing I am unsure is if I can just rerun the same .\signalbackup-tools_win.exe  --importfromdesktop <..> command, because after I restored the patched backup file with the data from Signal Desktop, I was automatically signed out on Signal Desktop and I had to relink the Signal Dektop app to the new Android installation. I am not sure if the bad data has now spread to the Signal Desktop installation.
>Can I reimport from the Signal Desktop app with the same command as before or do I need to restore the Signal Desktop app to a previous state first? I kept a copy from C:\Users\<user>\AppData\Roaming\Signal directory from right before I patched the Android backup file. And I kept the output of sigtop export-key from right before patching the backup file.

There is no chance of the bad data spreading to the Signal Desktop installation. There is little to no data exchange between the installations when linking (which is why old messages don't show up when linking a new device), but also, the data is not 'bad' for Signal Desktop: it is in a format that Signal Android did not like, but Desktop would be fine with it.

I don't think you need to restore Signal Desktop to a previous state. Just make sure you use the original Android backup file to import into. Otherwise, the bad data is of course already in there, and a second import would probably double a lot of messages.

>I am not sure if fixing the data inside the backup is easier. I am okay with losing the next two or 3 days of messages.

I think both are fairly easy. To fix the database without re-importing, you:
1. Export a new backup from your phone (just so it's up-to-date with the latest messages), and transfer it to your computer.
2. Run `signalbackup-tools [backup-file] [passphrase] --runsqlquery "UPDATE attachment SET upload_timestamp = JSONLONG(upload_timestamp) WHERE TYPEOF(upload_timestamp) = 'text'" --output [fixed_backup]`

That should be it. Please let me know if this solves your problem, or if you need any more help. Thanks!

**Comment by kwinz** [comment]
I can confirm that the bug is gone and works great now! The problem is solved! Thank you for the very fast bugfix!
