### ISSUE TITLE
Cant export database when attachment is damaged near 99.9%

### ISSUE THREAD

**Issue by MartB** [bepaald/signalbackup-tools#58]
Hey i tried to repair my backup file but it somehow fails to export with
```
Writing SharedPrefFrame(s)...
Writing KeyValueFrame(s)...
Writing Avatars...

WARNING: Bad MAC in attachmentdata: theirMac: (hex:) dc 9c 33 3a 9d 4b 85 55 0e 9b
                                      ourMac: (hex:) 5d 4e 1e 31 f2 31 ba 30 c1 6b bc 50 6d 94 34 21 fd 9b e4 f4 81 85 69 85 f9 51 78 4c 92 61 5a 6b
Failed to export backup to 'signal-good.backup'
```

If i use `--stoponbadmac`
```
FRAME 158847 (099.9%)...
WARNING: Bad MAC in frame: theirMac: (hex:) 94 40 ab 23 16 16 09 0a f2 c8
                             ourMac: (hex:) 4f 70 e6 0d 77 c9 09 e0 b3 01 cc 26 53 45 e6 69 b0 22 55 fc 72 3c b2 4d 3d ea 38 6f 4b dc e7 67
Stop reading backup. Next frame would be read at offset 4061737053
```

How can i still export the stuff thats "working" in this database?

**Comment by MartB** [comment]
Yep i can confirm after skipping over the avatar frames here: https://github.com/bepaald/signalbackup-tools/blob/c200d3d99cce19bf57ced2765e8d4ff69f15cb09/signalbackup/initfromfile.cc#L111 Got me all the other data back, now the groups / users seem to not have any avatars but i hope this will automagically fix itself.

Could be worth a shot to provide a --remove or ignore-avatars option.

**Comment by bepaald** [comment]
Hi thanks for this report!

I've pushed a fix for this, which automatically skips frames with corruption on write. This should have been default behavior, but was recently accidentally removed when I switched to the faster, less memory hungry, way of reading the backups. It should now simply skip single bad frames, while still being efficient, and automatically switch to full fixing mode when data corruption is more serious (i.e. bad data continues into the next frame).

One reason that this has gone unnoticed (I'm guessing) is because the Android app these days should actually be tolerant of this type of error, skipping the frame on import itself. But maybe it only does that with attachment data (and not avatars data)? Could you confirm that Signal refused to import the original backup?

If you have the time, I wouldn't mind if you ran the broken backup through the program again and let me know the output. I understand re-importing may be a hassle, so don't feel obligated. But, if you want to, I'd love to hear the results. If everything works, I suspect you will have all your avatars (except one) back. But I indeed _think_ the missing ones will automagically reappear eventually.

Thanks!

**Comment by MartB** [comment]
@bepaald Sure thing as the avatars did not re-appear i might aswell try it again.
The android app went through on the original but failed at the very last second with BAD MAC.

After restoring the "fixed" backup i made with the ugly hack from above the avatars are not coming back, so something is def. borked here. It tries to load an attachment but fails to do so and never tries to remove the entry from the database? or re-request it again.

**Comment by MartB** [comment]
Actually im not sure it would change anything if i now re-imported that, as this just "skips" the frames only right?
Something is telling signal that the avatar profile data is loaded and i kinda need to re-set this so it gets the correct parts again...

```
02-18 13:02:24.674  4872  4872 D BaseActivity: [MainActivity] onStart()
02-18 13:02:24.674  4872  4872 D LoggingFragment: [ConversationListFragmen] onStart()
02-18 13:02:24.685  4872 28135 W DecryptableStreamLocalU: null
02-18 13:02:24.685  4872 28135 W DecryptableStreamLocalU: java.io.IOException: No stream for: AttachmentId::(10914, 1644653043437)
02-18 13:02:24.685  4872 28135 W DecryptableStreamLocalU: 	at org.thoughtcrime.securesms.database.AttachmentDatabase.getAttachmentStream(AttachmentDatabase.java:208)
02-18 13:02:24.685  4872 28135 W DecryptableStreamLocalU: 	at org.thoughtcrime.securesms.mms.PartAuthority.getAttachmentStream(PartAuthority.java:73)
02-18 13:02:24.685  4872 28135 W DecryptableStreamLocalU: 	at org.thoughtcrime.securesms.mms.PartAuthority.getAttachmentThumbnailStream(PartAuthority.java:64)
02-18 13:02:24.685  4872 28135 W DecryptableStreamLocalU: 	at org.thoughtcrime.securesms.mms.DecryptableStreamLocalUriFetcher.loadResource(DecryptableStreamLocalUriFetcher.java:45)
02-18 13:02:24.685  4872 28135 W DecryptableStreamLocalU: 	at org.thoughtcrime.securesms.mms.DecryptableStreamLocalUriFetcher.loadResource(DecryptableStreamLocalUriFetcher.java:19)
02-18 13:02:24.685  4872 28135 W DecryptableStreamLocalU: 	at com.bumptech.glide.load.data.LocalUriFetcher.loadData(LocalUriFetcher.java:44)
02-18 13:02:24.685  4872 28135 W DecryptableStreamLocalU: 	at com.bumptech.glide.load.engine.SourceGenerator.startNextLoad(SourceGenerator.java:70)
02-18 13:02:24.685  4872 28135 W DecryptableStreamLocalU: 	at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:63)
02-18 13:02:24.685  4872 28135 W DecryptableStreamLocalU: 	at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:310)
02-18 13:02:24.685  4872 28135 W DecryptableStreamLocalU: 	at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:279)
02-18 13:02:24.685  4872 28135 W DecryptableStreamLocalU: 	at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:234)
02-18 13:02:24.685  4872 28135 W DecryptableStreamLocalU: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
02-18 13:02:24.685  4872 28135 W DecryptableStreamLocalU: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
02-18 13:02:24.685  4872 28135 W DecryptableStreamLocalU: 	at java.lang.Thread.run(Thread.java:920)
02-18 13:02:24.685  4872 28135 W DecryptableStreamLocalU: 	at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:393)
```

@bepaald Any idea which database magic is causing this to "remember" the attachment?

**Comment by bepaald** [comment]
Thanks for reporting back. Looking at the output it does seem like the program does what I wanted it to. And I can also see it successfully recovers from some corrupted frames earlier in the file. Just looking at the output, I would have guessed this was a good, working backup file.

I'm a bit confused about your last message, is that a log of the original fixed import, or the new fixed import? Does the app actually crash when you see this, or is it a caught and properly handled exception? What exactly are you doing when this exception occurs?

It looks to me like this exception is not about a missing avatar, but about a missing message attachment (AttachmentId::(10914, 1644653043437)). Attachments are identified by rowid and uniqueid (the latter is really just a timestamp), these values are stored in the 'part' table of the database. which for your backup seem to fit this range. What is strange however is 
1. Normally a missing attachment does not cause a crash as far as I know, there are natural circumstances where this happens (which is why the program only warns about them).
2. Looking at the "attachment data not found" warnings in the output of this program, 10914, 1644653043437 does not seem to be missing.

Unfortunately I'm not at home at the moment, so I can't really investigate thoroughly right now. But, I'd say, as long as the first fixed backup is no good anyway, try importing the new fixed backup and see if it makes a difference. Also, you could run `signalbackup-tools [fixed input] [password] --runsqlquery "SELECT * FROM part WHERE _id = 10914 AND unique_id = 1644653043437"`, and see if there is indeed an entry for this attachment.

>Something is telling signal that the avatar profile data is loaded

I would have to investigate, but I know there are things related to the profile (most notably 'signal_profile_avatar') in the 'recipient' table. Note also that profiles (and avatars) are not always immediately downloaded, I think that happens on some sort of timer.

When I get back home tomorrow, I will first remove some avatars from a backup to see if I can cause a crash (though I don't think so). And I'll think about this problem some more and hopefully think of some more things to try and fix this.

**Comment by MartB** [comment]
@bepaald thanks for taking the time to do some research.

I have to clarify that signal does not crash due to the avatars if removed, they just default display.
The new backup most likely works but it would probably also cause the missing avatars to be "stuck" in this java.io.Exception loop. Thats precisely the kind of thing we can try to fix / work around with some sql magic hopefully.

Imma try to take a look at the db / signals source later and see if i can find how to reset the profile / group icon state so it fetches it again.

**Comment by bepaald** [comment]
Still not home and not investigated, but just off the top of my head:

Every contact and group has an entry in the 'recipient' table. In the recipient table exists a column 'last_profile_fetch'. I suspect this is just a timestamp, which is hooked to the timer that occasionally downloads profiles. Maybe - if you've not been successful already - try setting this to zero (UPDATE recipient SET last_profile_fetch = 0), so the app thinks the profile needs re-fetching. It is also possible (if I had designed this I would have made it so) that when the timer fires, it only downloads some key that shows whether the profile has actually changed instead of immediately downloading the entire thing, so there is probably some other value that needs clearing for this to work (if t works at all). We might need to look at the source to figure that out.

Well, I'm off to work. Good luck!

**Comment by bepaald** [comment]
Sorry for the delay. Have you tried anything, and did it work?

I prepared a backup with the avatars removed. This is a small backup, with only three recipients with an avatar (two groups and one individual). After some playing and clearing various entries in the database, the closest I got was using `"UPDATE recipient SET last_profile_fetch = 0, signal_profile_avatar = NULL"`, and then restoring the backup. Clearing the _profile_key_ seemed to cause problems, and clearing anything in the _groups_ table doesn't seem to help (in fact, all avatar-related fields in that table were already empty).

After restore, 2 of the three (one group and the individual) avatars immediately reappeared. The third did not (and still has not, this was yesterday). I do not know if there something weird that causes the last one to not appear, or if there is something weird that causes the other two to. So, you could try doing the same, maybe you will get lucky.

If it doesn't work, I'm out of ideas for now, but it should actually be fairly easy to import the avatar from a different (older, non-broken) backup if you have one. Let me know if we need to work on that.

Lastly, I can at least confirm that if the profile-avatar is changed, it will update anyway. So, depending on your relationship with the people in the group, you could also just ask someone to update it (and change it back if necessary).

**Comment by MartB** [comment]
Yeah i ran a similar sql query to clear the profile avatars, this ended up re-fetching okay.
Group avatars indeed did not get re-fetched even after playing with the table, i got all the groups to manually change pictures though, so thats fine hehe

This issue can now be closed and kept as reference, as i assume its a pretty niche error.
If you really wanted to you could add some quick "clear" avatar functionality if an avatar frame is corrupt, but i will leave that up to you :)

Thanks for this project and your continous effort @bepaald i really appreciate it!
🚀

**Comment by bepaald** [comment]
>Yeah i ran a similar sql query to clear the profile avatars, this ended up re-fetching okay.
Group avatars indeed did not get re-fetched even after playing with the table, i got all the groups to manually change pictures though, so thats fine hehe

Excellent

>This issue can now be closed and kept as reference, as i assume its a pretty niche error.
If you really wanted to you could add some quick "clear" avatar functionality if an avatar frame is corrupt, but i will leave that up to you :)

Yeah, I think that's not a bad idea, even if hardly anyone ever runs into this. I'm glad at least the program did what it was meant to (make an unrestorable backup restorable), but clearing the avatar data in the sqlite database would be a nice feature as long as I can determine automatically _which_ contacts' data needs to be cleared. If I can't and users need to do it manually anyway, I think the `runsqlquery` option will suffice for this rare case. I'll put it somewhere in the to-do list.

>Thanks for this project and your continous effort @bepaald i really appreciate it!

Thanks for your kind words. Happy to help!
